// ddrive — Server-rendered /login entry page (thin SEO shell).
//
// This page is a thin entry into the SPA at /app/login — not a target for
// organic search traffic (that lives on /). It exists so that:
//   - branded "ddrive login" searches can land here with a clear CTA,
//   - links from external sites (e.g. GitHub README "Sign in" link) point
//     to a stable, non-SPA URL that explains the page in 5 lines.
//
// To avoid competing with the canonical landing page in search rankings:
//   - noindex, follow: this page is not in the index, but links from it
//     still pass link equity to other pages on the site.
//   - canonical: /  — search engines that see this URL consolidate the
//     signal to the main landing page instead of treating it as duplicate.
//   - no JSON-LD / FAQ / structured data — keep the page light.

import { escapeHtml, publicOrigin, renderMetaTags } from "./seo-helpers.js";

const META: Parameters<typeof renderMetaTags>[1] = {
  title: "Sign in — ddrive",
  description:
    "Sign in to ddrive to manage, organize and stream your files.",
  path: "/login",
  ogType: "website",
  // Override the default robots to noindex while keeping the canonical
  // pointing at / so this thin page never competes in SERPs.
  robots: "noindex, follow",
};

const BODY_HTML = `
<div id="root">
  <header class="topbar">
    <a class="brand" href="/">ddrive</a>
    <nav>
      <a href="/drop">Drop a file</a>
      <a href="/login">Sign in</a>
    </nav>
  </header>
  <main>
    <section class="hero">
      <h1>Sign in to ddrive</h1>
      <p class="lede">Manage, organize and stream your files. The sign-in form lives in the ddrive app.</p>
      <p class="cta">
        <a class="btn primary" href="/app/login">Open the sign-in form</a>
        <a class="btn" href="/">Back to home</a>
      </p>
    </section>
    <section id="also">
      <p>No account yet? You can <a href="/drop">drop a file</a> without signing in &mdash; anonymous shares work for 30 days.</p>
    </section>
    <section id="disclaimer" class="disclaimer">
      <p><strong>Proof of concept.</strong> ddrive is provided as-is, with no uptime or reliability guarantees. Files may be deleted or corrupted at any time. Don't use ddrive as the only copy of important data.</p>
    </section>
  </main>
  <footer>
    <p>&copy; ddrive. <a href="/">Home</a> &middot; <a href="/drop">Drop a file</a> &middot; <a href="/sitemap.xml">Sitemap</a></p>
  </footer>
</div>
`;

const STYLE = `
<style>
  :root { color-scheme: light dark; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Inter, sans-serif;
         margin: 0; background: #0b0d10; color: #e8eaed; line-height: 1.55; }
  .topbar { display: flex; align-items: center; justify-content: space-between;
            padding: 16px 24px; border-bottom: 1px solid #1c1f24; }
  .brand { font-weight: 700; font-size: 20px; color: #e8eaed; text-decoration: none; }
  .topbar nav a { color: #9aa0a6; text-decoration: none; margin-left: 20px; font-size: 14px; }
  .topbar nav a:hover { color: #e8eaed; }
  main { max-width: 760px; margin: 0 auto; padding: 32px 24px 64px; }
  h1 { font-size: 30px; line-height: 1.2; margin: 24px 0 12px; }
  .lede { font-size: 17px; color: #c2c5cb; margin: 0 0 24px; }
  .cta { display: flex; gap: 12px; flex-wrap: wrap; }
  .btn { display: inline-block; padding: 10px 18px; border-radius: 8px;
         text-decoration: none; font-size: 14px; font-weight: 500;
         border: 1px solid #3c4043; color: #e8eaed; background: transparent; }
  .btn.primary { background: #6366f1; border-color: #6366f1; color: white; }
  .btn:hover { filter: brightness(1.1); }
  a { color: #8ab4ff; }
  .disclaimer { margin-top: 32px; padding: 12px 16px; border: 1px solid #4a2c2c; border-radius: 8px; background: #1a0f0f; }
  .disclaimer p { color: #d6b6b6; font-size: 13px; margin: 0; }
  .disclaimer strong { color: #f5a3a3; }
  footer { border-top: 1px solid #1c1f24; padding: 24px; text-align: center;
           color: #9aa0a6; font-size: 13px; }
  footer a { color: #9aa0a6; }
  @media (max-width: 600px) { h1 { font-size: 24px; } .topbar { padding: 12px 16px; } }
</style>
`;

export async function handleLoginPage(req: Request): Promise<Response> {
  const title = META.title;
  const metaTags = renderMetaTags(req, META);
  // Override canonical to point at the main landing page so this thin
  // entry page never competes in SERPs. og:url and the path-derived
  // canonical generated by renderMetaTags are both replaced by the same
  // single tag below. publicOrigin honors X-Forwarded-Proto so this is
  // https:// in production (where TLS terminates at nginx).
  const canonicalHref = `${publicOrigin(req)}/`;
  const cleanedMetaTags = metaTags
    .split("\n")
    .filter((line) => !line.includes('rel="canonical"') && !line.includes('property="og:url"'))
    .join("\n");
  const canonicalTags = [
    `<link rel="canonical" href="${escapeHtml(canonicalHref)}" />`,
    `<meta property="og:url" content="${escapeHtml(canonicalHref)}" />`,
  ].join("\n");

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(title)}</title>
${cleanedMetaTags}
${canonicalTags}
${STYLE}
</head>
<body>
${BODY_HTML}
</body>
</html>`;

  return new Response(html, {
    status: 200,
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=3600",
    },
  });
}
